title: Saber Atual
description: >
  Atualidades e estudos preparatórios para vestibulares, concursos e qualificação profissional.
  Solicite o Saber Atual na sua escola.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saberatual.net"

# Build settings
markdown: kramdown
exclude:
  - desktop.ini
  - gulpfile.js
  - README.md

sass:
  style: compressed

gems:
  - jekyll-coffeescript


